apiVersion: req.nephio.org/v1alpha1
kind: DataNetwork
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: "2024-10-07T11:30:29Z"
  finalizers:
  - req.nephio.org.dnns.claim
  - req.nephio.org.dnns.ready
  managedFields:
  - apiVersion: req.nephio.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:api.choreo.kform.dev/origin: {}
      f:spec:
        f:network: {}
        f:pools: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-10-07T11:30:29Z"
  - apiVersion: req.nephio.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"req.nephio.org.dnns.claim": {}
      f:status:
        f:conditions:
          k:{"type":"ClaimReady"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: req.nephio.org.dnns.claim
    operation: Apply
    time: "2024-10-07T11:30:29Z"
  - apiVersion: req.nephio.org/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          v:"req.nephio.org.dnns.ready": {}
      f:status:
        f:conditions:
          k:{"type":"Ready"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:pools: {}
    manager: req.nephio.org.dnns.ready
    operation: Apply
    time: "2024-10-07T11:30:29Z"
  name: nephio.internet.ipv4
  namespace: default
  resourceVersion: "2"
  uid: a75d8873-1c29-4cea-a954-6a8a104d0b5b
spec:
  network: vpc-internet
  pools:
  - ipFamilyPolicy: ipv4-only
    name: pool1
    prefixLength: 24
status:
  conditions:
  - lastTransitionTime: "2024-10-07T11:30:29Z"
    message: ""
    reason: Ready
    status: "True"
    type: ClaimReady
  - lastTransitionTime: "2024-10-07T11:30:29Z"
    message: ""
    reason: Ready
    status: "True"
    type: Ready
  pools:
  - ipv4:
      prefixes:
      - prefix: 10.0.0.0/24
    name: pool1
