apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: null
  name: req.kuid.dev.attachments.all
spec:
  code:
    reconciler.star: "load(\"api.k8s.io.object.star\", \"getName\", \"getNamespace\",
      \"getDeletionTimestamp\", \"delFinalizer\", \"setFinalizer\")\nload(\"req.kuid.dev.attachments.star\",
      \"setStatusPrefix\", \"setStatusVLAN\")\n\nfinalizer = \"req.kuid.dev.networks.all\"\nconditionType
      = \"Ready\"\n\ndef reconcile(self):\n  #self is prefix req\n\n  if getDeletionTimestamp(self)
      != None:\n    rsp = client_delete()\n    if rsp[\"error\"] != None:\n      return
      reconcile_result(self, True, 0, conditionType, rsp[\"error\"], rsp[\"fatal\"])\n
      \   \n    delFinalizer(self, finalizer)\n    return reconcile_result(self, False,
      0, conditionType, \"\", False)\n\n  setFinalizer(self, finalizer)\n\n  attachmentName
      = getName(self)\n  if attachmentName == \"nephio.region1.us-east1.cluster1.upf1.n3\":\n
      \   setStatusPrefix(self, \"ipv4\", \"192.1.0.0/24\", \"192.1.0.1\")\n    setStatusPrefix(self,
      \"ipv6\", \"192:1::/64\", \"192:1::1\")\n    setStatusVLAN(self, 1)\n  elif
      attachmentName == \"nephio.region1.us-east1.cluster1.upf1.n4\":\n    setStatusPrefix(self,
      \"ipv4\", \"192.2.0.0/24\", \"192.2.0.1\")\n    setStatusPrefix(self, \"ipv6\",
      \"192:2::/64\", \"192:2::1\")\n    setStatusVLAN(self, 2)\n  elif attachmentName
      == \"nephio.region1.us-east1.cluster1.upf1.n6\":\n    setStatusPrefix(self,
      \"ipv4\", \"192.3.0.0/24\", \"192.3.0.1\")\n    setStatusPrefix(self, \"ipv6\",
      \"192:3::/64\", \"192:3::1\")\n    setStatusVLAN(self, 3)\n  \n  return reconcile_result(self,
      False, 0, conditionType, \"\", False)\n"
  for:
    group: req.kuid.dev
    kind: Attachment
    selector: {}
    version: v1alpha1
  type: starlark
status: {}
