apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
metadata:
  annotations:
    api.choreo.kform.dev/origin: '{"kind":"File"}'
  creationTimestamp: "2024-10-07T11:30:29Z"
  managedFields:
  - apiVersion: choreo.kform.dev/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:api.choreo.kform.dev/origin: {}
      f:spec:
        .: {}
        f:code:
          .: {}
          f:reconciler.star: {}
        f:for:
          .: {}
          f:group: {}
          f:kind: {}
          f:selector: {}
          f:version: {}
        f:type: {}
      f:status: {}
    manager: inputfileloader
    operation: Apply
    time: "2024-10-07T11:30:29Z"
  name: req.kuid.dev.prefixes.all
  resourceVersion: "0"
  uid: 893c9ba9-2286-40ad-af50-9e55ab9b1064
spec:
  code:
    reconciler.star: "load(\"api.k8s.io.object.star\", \"getName\", \"getNamespace\",
      \"getDeletionTimestamp\", \"delFinalizer\", \"setFinalizer\")\nload(\"req.kuid.dev.prefixes.star\",
      \"setStatusPrefix\")\n\nfinalizer = \"req.kuid.dev.prefixes.all\"\nconditionType
      = \"Ready\"\n\ndef reconcile(self):\n  #self is prefix req\n\n  if getDeletionTimestamp(self)
      != None:\n    rsp = client_delete()\n    if rsp[\"error\"] != None:\n      return
      reconcile_result(self, True, 0, conditionType, rsp[\"error\"], rsp[\"fatal\"])\n
      \   \n    delFinalizer(self, finalizer)\n    return reconcile_result(self, False,
      0, conditionType, \"\", False)\n\n  setFinalizer(self, finalizer)\n\n  if getName(self)
      == \"nephio.vpc-internet.pool1.ipv4\":\n    setStatusPrefix(self, \"10.0.0.0/24\")\n
      \ \n  return reconcile_result(self, False, 0, conditionType, \"\", False)\n"
  for:
    group: req.kuid.dev
    kind: Prefix
    selector: {}
    version: v1alpha1
  type: starlark
status: {}
