
apiVersion: choreo.kform.dev/v1alpha1
kind: Reconciler
# name can be inferred from the filename or from the for resource
spec: 
  for: 
    group: req.nephio.org
    version: v1alpha1
    kind: DataNetwork
    selector: {}
  owns:
  - group: req.kuid.dev
    version: v1alpha1
    kind: Prefix
